# Generated by Django 5.2.9 on 2026-01-08 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="created_at",
        ),
    ]
