# Generated by Django 5.2.9 on 2026-01-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_device_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="manual",
            field=models.FileField(blank=True, null=True, upload_to="manuals/"),
        ),
    ]
