# Generated by Django 5.2.9 on 2026-01-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_device_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="has_embeddings",
            field=models.BooleanField(default=False),
        ),
    ]
